### ISSUE TITLE
Romanized search warning inconsistent

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1198]
Romanized searching gives message when pressing enter with three words, yet live search is able to search with one word. Need to disable warning about four words or enforce it at live search level.

![image](https://user-images.githubusercontent.com/27791330/89097180-80a16180-d391-11ea-9fcd-6ff8cd37187c.png)

**Comment by ManjotS** [comment]
Please enforce because it works poorly at less than 3

**Comment by plug-n-play** [comment]
Don't see a warning to user to enter another word to get a valid result:

![image](https://user-images.githubusercontent.com/6245927/104154558-3b3a9300-540b-11eb-9fd2-b0420e7cdb8b.png)

**Comment by plug-n-play** [comment]
Update: I observe the message only when user clicks the enter/return key, not on it's own. This is a broken experience since the actual results start showing up in the drop down as user types. IMO, we should also show a message to user that he needs to enter more words in order to auto populate search results. The current experience is broken and gives user a signal that this very functionality doesn't works.
