### ISSUE TITLE
Add option to display options to remove ALL sharing links

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#122]

**Comment by bogas04** [comment]
Do we need this as we hide them for mobile and show those only on hover for desktop?

**Comment by ManjotS** [comment]
prefer the option

**Comment by bogas04** [comment]
Where should we keep this option then?

**Comment by tarunsingh5** [comment]
i think you put the < logo and when ppl click that it pops down w/ the share options

**Comment by ManjotS** [comment]
@tarunsingh5 this ticket is to remove all sharing links from the page as an option. As said in the title its a toggle in the display drop down.

**Comment by bogas04** [comment]
Okay;

We show share button only when page is scrolled to top.

* On mobile without WebShare API, we show one sharing option; WhatsApp button
* On mobile with WebShare API, we show one sharing option; Share button
* On desktop without WebShare API, we show on sharing option; Embed
* On desktop with WebShare API, we show 2 sharing options; Embed and Share.
* On desktop upon hovering a line, we 1 sharing option, tweet button.

Apart from that, we've short URL and copy button.

Since the share button doesn't really come in the way, I am not sure if this will change anything as we still show Display Options, Font Options, Larivaar and Larivaar Assist option all the time.

I think, we can instead have a full screen option on mobile, that hides the sticky bar for better reading experience. They can access it again by scrolling to top, clicking "Display Options" and then disabling it. If we get enough traction via analytics, we can evolve the feature further.

What do you think? @saintsoldierx @tarunsingh5

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/50064723-7f450600-0167-11e9-9bf2-2bc6241c4c9e.png)

@bogas04 i think this ticket is in reference to the sharing links line by line on a shabad as per the screenshot...

**Comment by ManjotS** [comment]
yes this is just to hide the sharing link

**Comment by bogas04** [comment]
Can we implement this in a better way instead? We can't access this on mobile, and on desktop it can be annoying.

**Comment by saintsoldierx** [comment]
Refer to #668
