### ISSUE TITLE
Add a dropdown to select Bani length for SG

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1268]
Add ability to select Bani length for Sunder Gutka - default should be SHORT.

![image](https://user-images.githubusercontent.com/27791330/94983854-5ab44c80-04fb-11eb-9657-455fe02e18e5.png)

**Comment by plug-n-play** [comment]
Working as expected.

@saintsoldierx Suggested change: IMHO it's better to have this option at Baani level rather than at Sundar Gutka level. For example, if user is reciting Choupai Sahib but realises he wants to read longer/shorter version while reciting it, he should be able to do it from read mode itself rather than switching back and forth and checking different versions - Short-to-Extra-Long. If we agree, we can create a new ticket for this
