### ISSUE TITLE
Shabad writer does not always show

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1347]
When viewing some shabads, the writer does not show. In some other shabads, they do. It does seem at first look that only shabads written by bhagats are showing. Shabads written by Gurus does not show the name of the Guru.

Does not show:
![image](https://user-images.githubusercontent.com/27791330/108030217-b5020580-6fe3-11eb-9ab2-d86a38995877.png)

Does show:
![image](https://user-images.githubusercontent.com/27791330/108030238-c0edc780-6fe3-11eb-91f7-f2831c4001d4.png)

**Comment by navdeepsingh** [comment]
@saintsoldierx the data coming from BaniDB doesn't contain Writer info https://api.khajana.org/v2/shabads/2523

![Screen Shot 2021-03-01 at 4 39 44 PM](https://user-images.githubusercontent.com/2968787/109490097-c4865180-7aad-11eb-8215-87a9238c7f61.png)

That's why it doesn't show in the first place.

**Comment by saintsoldierx** [comment]
This has been fixed and merged in PROD.
