### ISSUE TITLE
Add main letter search (fuzzy search)

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#141]
Should also disable lagamatras/modifiers in input box AND onscreen keyboard when selected

**Comment by ManjotS** [comment]
I added it to API some time ago. Search type 6

**Comment by bogas04** [comment]
Awesome, will add it to shabados-js.

**Comment by irvanjit** [comment]
This should also be extended to handle edge cases where characters like ਓ are whole akhars instead of a base akhar modified with lagamatra'n. So a search with akhar ੳ should intuitively give results with both ੳ and ਓ. Not sure if it makes sense to implement this at the db level or not. @bogas04 @ManjotS

**Comment by ManjotS** [comment]
@bogas04 when will this be added?

@irvanjit the char replacement will be added to api as part of the ability to use unicode and ascii

**Comment by bogas04** [comment]
Is it part of BaniDB 2?

**Comment by saintsoldierx** [comment]
@ManjotS please connect again with Divjot Singh on this.

**Comment by ManjotS** [comment]
Waiting on API 2
