### ISSUE TITLE
Use infinite searching instead of pagination

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#287]
when searching, clicking load more should keep track of page, ie adding #page-2 to the url.

This in turn means when a link is loaded with that anchor tag, it scrolls to that position.

**Comment by bogas04** [comment]
Already fixed in dev. 
Instead of scrolling, we just paginate everything like google.

`http://dev.sikhitothemax.org/search?q=hhh&source=all&type=0`
➡️ Load More
`http://dev.sikhitothemax.org/search?q=hhh&source=all&type=0&offset=1`
➡️ Load More
`http://dev.sikhitothemax.org/search?q=hhh&source=all&type=0&offset=2`

**Comment by ManjotS** [comment]
can we have it auto scroll to that position.. ie when loading http://dev.sikhitothemax.org/search?q=hhh&source=all&type=0&offset=3 it should show the first result of offset 3

**Comment by bogas04** [comment]
Does it not?

**Comment by ManjotS** [comment]
not in FF

**Comment by bogas04** [comment]
I don't understand. Earlier we used to append load more results to the same page, now we just load a new page with those results, so it's always on top, isn't it?

**Comment by ManjotS** [comment]
it should be loading new results at the bottom

**Comment by bogas04** [comment]
That behaviour is complicated as we've to fetch offset 0,1,...n, add to page, and then scroll to that offset results. This is bad for bandwidth, performance and experience.

So I changed it to just load that offset's results only. No more appending of results. If user wants to see previous page, s/he hits back button. Maybe we can have `1 | 2 | next` instead of load more.

**Comment by saintsoldierx** [comment]
I think we need to have the page numbers (pagination) and have "next page" instead of "load more". Personally, i like the infinity scrolling feature.

**Comment by bogas04** [comment]
Infinite scrolling, while is good, comes with a lot of challenges to make it accessible. Even Google doesn't do it.

Anyway, since Sehaj Paath View would be something like this, I'll take this up with that. For now, I'll show next and previous page buttons instead of load more. Works?
