### ISSUE TITLE
Sundar Gutka Paragraph Mode

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#541]
**Describe the solution you'd like**
Let's bring the split view option back in the settings but in gutka it should use the paragraph column in Banis_Shabad for groupings.

It's especially difficult to read dasam bani right now where each line is a single word.

**Comment by bogas04** [comment]
@navdeepsinghkhalsa if i understand it right, API sends `paragraph: number` for each line, and client can aggregate them all based on that. Right? I've implemented this in the PR #584

**Comment by saintsoldierx** [comment]
So we have split view back for STTM searches - just not in Sunder Gutka and i think that's fine. Because of the great lengths of some of the Banis in SG, it doesn't make sense to have split mode anyway. If users just want one or the other, they can toggle off/on translit, translations, Gurmukhi and so forth.

**Comment by ManjotS** [comment]
split view was scoped for SG as being per paragraph (ie paragraph mode)

**Comment by saintsoldierx** [comment]
@ManjotS can you expand more on this ticket as to exactly what the requirement is? I am not getting it. If needed, I will reopen and scope it.

**Comment by ManjotS** [comment]
see paragraph mode in the SG app. its line by line vs verse by verse. the data is in the api.
