### ISSUE TITLE
Sharing integration should preserve larivaar setting for Gurmukhi text

### ISSUE THREAD

**Issue by irvanjit** [KhalisFoundation/sttm-web#56]
For sharing/social media links, larivaar settings should be preserved for the Gurmukhi if the setting is enabled.

**Comment by bogas04** [comment]
We preserve it for copying the text. But for the short URLs, this would mean updating our URL shortening scheme, which will make it, well, not short.

Another thing is that, I feel Larivaar or not should be not decided by sharer but rather the user.

Consider this;

I've larivaar enabled on my system, but my friend has it disabled. They shared a link with me, and it opens without larivaar because their larivaar setting is preserved and my preference is not. This is bad for me as I use larivaar.

Now consider other scenario, I share a link to my friend, and they had larivaar with larivaar assist enabled on their system, however my link only has larivaar, and they have to again choose larivaar Assist to read it as per their liking.

Eventually, this will make the preferences system unintuitive. For some links it shows as per your settings, but for others it would show as per the setting the person who shared had. What is the point of preference when it isn't maintained consistently? 

@saintsoldierx @ManjotS need your opinion here.

**Comment by ManjotS** [comment]
Agree. User prefs should come first.

**Comment by bogas04** [comment]
So does this make the issue a WONTFIX?

**Comment by saintsoldierx** [comment]
I agree with you too. Let's close this.
