### ISSUE TITLE
Web User Bug Reports : local storage in FF

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#800]
Please select which platform you are using:-
Desktop Version

Feedback Type
Bug Reports

What went wrong?
in Firefox (v69.0 64bit) in the local storage it do not store the translation language info. Therefore, whenever I open the website I have to adjust the settings for translation. 

Thanks for this awesome resource. This is of immense help to me. Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh.
 
What should have happened instead?
It should save the translation settings. 
    
How can the issue be recreated by our team?
Just change the translation settings on the website in  Firefox (v69.0 64bit). Refresh the page. You will see the translation settings reset to default.

Which web browser are using?
FireFox 69

Operating System
Mac OS

Name
Navjinder Singh

**Comment by gurpreet-hanjra** [comment]
Hello, it's not reproducible on Firefox. Maybe it's issue with user's browser or system.

**Comment by Gauravjeetsingh** [comment]
@gurpreet-hanjra ji, here are the steps to reproduce it:
( I tested it in chrome)
- Search for any shabad
- Go to display settings, and change the translation toggles 
(Show all the translations: English, punjabi and spanish)
- Refresh the page
- **Expected behavior**: The translation toggle should be in the way it was before refreshing (We should see all the translations; english, punjabi and spanish)
- **What actually happens?**: We only see english translation.

Possible reason: Some bug with saving the translation settings in browser's local storage.

Also, can you give me your email id, so that I can invite you to the official slack channel of khalis. There's a dedicated channel for sttm-web. You can discuss/ask your doubts (if any) there.

**Comment by gurpreet-hanjra** [comment]
Thank you for the reply and letting know about discussions. I will try reproducing again. 
my email id is gurpreet.hanjra@gmail.com
