### ISSUE TITLE
Search Operators and Highlighting not working

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-web#988]
https://stg.sikhitothemax.org/search?q=kIrqn%20%2B%20rhwau&type=2&source=all

Should highlight both words but highlights first word and next two words

**Comment by ManjotS** [comment]
please assign to @turbanpanda

**Comment by Gauravjeetsingh** [comment]
Need the API to show results with search operators. The highlighting part is done and deployed to prod.

**Comment by tarunsingh5** [comment]
@Manjot Singh <manjot@manjotsingh.net> whats the update here

**Comment by ManjotS** [comment]
I don't understand what the API needs to do here

**Comment by tarunsingh5** [comment]
please sync w/ Gaurav directly

**Comment by ManjotS** [comment]
thats what I am doing. @Gauravjeetsingh what does the API need to do here? Can you make an API ticket with your requirements?

**Comment by Gauravjeetsingh** [comment]
@ManjotS veerji, I am not sure the root cause, maybe a newer deployment is needed. Search operators still give 0 results with the Banidb API. But they work fine in Khajana API.

BaniDB API with 0 search results: https://api.banidb.com/v2/search/hj*r?source=all&page=1
Khajana API with search results: https://api.khajana.org/v2/search/hj*r?source=all&page=1

**Comment by manjot** [comment]
Why am I in this email thread?

Kindly exclude my email address.

**Comment by Gauravjeetsingh** [comment]
It's working on prod now. Closing this up.
